@extends('layouts.app') @section('title',$question->exists?'Edit Soal':'Buat Soal') @section('content')
<div class="mb-6"><h2 class="text-3xl font-black">{{$question->exists?'Edit Soal':'Buat Soal'}}</h2><p class="text-slate-500">Tulis soal dan pembahasan dengan editor rumus yang mudah digunakan.</p></div>
<form method="post" action="{{$question->exists?route('questions.update',$question):route('questions.store')}}" class="space-y-5">@csrf @if($question->exists) @method('PUT') @endif
@if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700"><div class="font-black">Soal belum tersimpan. Periksa bagian berikut:</div><ul class="mt-2 list-disc pl-5 text-sm">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<div class="grid gap-4 rounded-3xl bg-white p-6 shadow-sm md:grid-cols-4"><label class="font-bold">Subtest<select name="subject_id" required class="mt-2 w-full rounded-xl border-slate-200">@foreach($subjects as $s)<option value="{{$s->id}}" @selected(old('subject_id',$question->subject_id)==$s->id)>{{$s->name}}</option>@endforeach</select></label><label class="font-bold">Materi<select name="topic_id" class="mt-2 w-full rounded-xl border-slate-200"><option value="">Tanpa materi</option>@foreach($subjects as $s)@foreach($s->topics as $t)<option value="{{$t->id}}" @selected(old('topic_id',$question->topic_id)==$t->id)>{{$s->name}} - {{$t->name}}</option>@endforeach @endforeach</select></label><label class="font-bold">Jenis<select id="type" name="type" class="mt-2 w-full rounded-xl border-slate-200"><option value="multiple_choice" @selected(old('type',$question->type)==='multiple_choice')>Pilihan Ganda</option><option value="essay" @selected(old('type',$question->type)==='essay')>Esai</option></select></label><label class="font-bold">Kesulitan<select name="difficulty" class="mt-2 w-full rounded-xl border-slate-200">@foreach(['easy'=>'Mudah','medium'=>'Sedang','hard'=>'Sulit'] as $v=>$l)<option value="{{$v}}" @selected(old('difficulty',$question->difficulty?:'medium')===$v)>{{$l}}</option>@endforeach</select></label></div>
@include('questions.editor')
<div id="mc" class="rounded-3xl bg-white p-6 shadow-sm"><h3 class="text-lg font-black">Pilihan Jawaban</h3>@foreach(['A','B','C','D','E'] as $label)@php $op=$question->options?->firstWhere('option_label',$label); @endphp<div class="mt-3 flex items-center gap-3"><input required type="radio" name="correct_answer" value="{{$label}}" @checked(old('correct_answer',$question->options?->firstWhere('is_correct',true)?->option_label)===$label)><b>{{$label}}.</b><input name="options[{{$label}}]" value="{{old('options.'.$label,$op?->option_text)}}" class="w-full rounded-xl border-slate-200" placeholder="{{$label==='E'?'Opsional':'Isi pilihan'}}"></div>@endforeach</div>
<div id="essay" class="grid gap-4 rounded-3xl bg-white p-6 shadow-sm md:grid-cols-3"><label class="font-bold">Instruksi<textarea name="instructions" class="mt-2 w-full rounded-xl border-slate-200">{{old('instructions',$question->instructions)}}</textarea></label><label class="font-bold">Kunci Referensi<textarea name="answer_key" class="mt-2 w-full rounded-xl border-slate-200">{{old('answer_key',$question->answer_key)}}</textarea></label><label class="font-bold">Rubrik<textarea name="rubric" class="mt-2 w-full rounded-xl border-slate-200">{{old('rubric',$question->rubric)}}</textarea></label></div>
<div class="grid gap-4 rounded-3xl bg-white p-6 shadow-sm md:grid-cols-3"><label class="font-bold">Bobot<input type="number" step=".01" name="score" value="{{old('score',$question->score?:10)}}" class="mt-2 w-full rounded-xl border-slate-200"></label><label class="font-bold">Kelas<input name="class_level" value="{{old('class_level',$question->class_level)}}" class="mt-2 w-full rounded-xl border-slate-200"></label><label class="font-bold">Status<select name="status" class="mt-2 w-full rounded-xl border-slate-200"><option value="active">Aktif</option><option value="inactive" @selected(old('status',$question->status)==='inactive')>Nonaktif</option></select></label></div><div class="flex flex-col-reverse gap-3 sm:flex-row"><a href="{{route('questions.index')}}" class="btn-action rounded-2xl border border-slate-300 bg-white px-8 text-slate-700">Kembali ke Bank Soal</a><button type="submit" class="btn-action btn-primary-solid rounded-2xl px-8">Simpan Soal</button></div></form>
@include('questions.editor-script')@endsection
