@extends('layouts.app')
@section('title', $meetingAssignment->title)
@section('content')
<div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('meeting-assignments.index') }}" class="text-sm font-black text-indigo-600">← Kembali</a><h2 class="mt-3 text-3xl font-black">{{ $meetingAssignment->title }}</h2><p class="mt-2 font-bold text-indigo-600">{{ $meetingAssignment->classroom->title }} · {{ $meetingAssignment->classroom->branch }} · {{ $meetingAssignment->meeting_date->format('d M Y') }}</p></div>@if(auth()->user()->role !== 'student')<form method="post" action="{{ route('meeting-assignments.destroy', $meetingAssignment) }}" onsubmit="return confirm('Hapus tugas pertemuan ini beserta semua karya siswa?')">@csrf @method('DELETE')<button class="rounded-xl bg-rose-50 px-5 py-3 font-black text-rose-600">Hapus</button></form>@endif</div>
<div class="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-black">Instruksi</h3><div class="mt-3 whitespace-pre-wrap leading-7 text-slate-600">{{ $meetingAssignment->instructions ?: 'Tidak ada instruksi tambahan.' }}</div><div class="mt-4 text-sm font-bold text-slate-500">Batas pengumpulan: {{ $meetingAssignment->due_at->format('d M Y H:i') }}</div></div>

@if(auth()->user()->role === 'student')
  <section class="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="text-xl font-black">Pengumpulan Karya</h3>
    @if($submission)<div class="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Karya dikumpulkan {{ $submission->submitted_at->format('d M Y H:i') }}. Kehadiran tercatat otomatis. @if($submission->score !== null)<br>Nilai: {{ $submission->score }}/{{ $meetingAssignment->max_score }}@endif</div><div class="mt-3 flex flex-wrap gap-4"><a target="_blank" href="{{ route('meeting-submissions.file', $submission) }}" class="font-black text-indigo-600">Lihat karya yang dikirim</a>@if($submission->drive_sync_status === 'synced' && $submission->drive_web_view_link)<a target="_blank" rel="noopener" href="{{ $submission->drive_web_view_link }}" class="font-black text-emerald-600">Buka arsip Google Drive</a>@elseif($submission->drive_sync_status === 'pending' || $submission->drive_sync_status === 'syncing')<span class="font-bold text-amber-600">Arsip Google Drive sedang diproses</span>@elseif($submission->drive_sync_status === 'failed')<span class="font-bold text-rose-600">Arsip Google Drive gagal; file lokal tetap aman</span>@endif</div>@if($submission->feedback)<div class="mt-4 rounded-2xl bg-indigo-50 p-4"><b>Catatan mentor:</b><p class="mt-2 whitespace-pre-wrap text-slate-700">{{ $submission->feedback }}</p></div>@endif @endif
    @if(now()->lte($meetingAssignment->due_at))<form method="post" action="{{ route('meeting-assignments.submit', $meetingAssignment) }}" enctype="multipart/form-data" class="mt-5 space-y-4">@csrf<label class="block font-bold">File karya (JPG, PNG, WEBP, atau PDF; maksimal 10 MB)<input type="file" name="work" accept="image/jpeg,image/png,image/webp,application/pdf" required class="mt-2 block w-full rounded-xl border border-slate-300 p-3"></label><label class="block font-bold">Catatan<textarea name="note" rows="3" class="mt-2 w-full rounded-xl border-slate-300"></textarea></label><button class="btn-action btn-primary-solid rounded-2xl px-6">{{ $submission ? 'Perbarui Karya' : 'Kumpulkan Karya & Catat Hadir' }}</button></form>@else<p class="mt-5 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">Batas pengumpulan telah berakhir.</p>@endif
  </section>
@else
  <section class="mt-6"><h3 class="text-xl font-black">Karya Siswa ({{ $meetingAssignment->submissions->count() }})</h3><div class="mt-4 grid gap-4 lg:grid-cols-2">@forelse($meetingAssignment->submissions as $item)<article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex justify-between gap-3"><div><h4 class="font-black">{{ $item->student->name }}</h4><p class="text-xs text-slate-400">{{ $item->submitted_at->format('d M Y H:i') }}</p></div><a target="_blank" href="{{ route('meeting-submissions.file', $item) }}" class="font-black text-indigo-600">Lihat Karya</a></div><div class="mt-3 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600">Google Drive: {{ ['pending'=>'Menunggu antrean','syncing'=>'Sedang sinkron','synced'=>'Tersimpan','failed'=>'Gagal','disabled'=>'Tidak aktif'][$item->drive_sync_status] ?? $item->drive_sync_status }} @if($item->drive_sync_status === 'synced' && $item->drive_web_view_link)<a target="_blank" rel="noopener" href="{{ $item->drive_web_view_link }}" class="ml-2 text-emerald-600">Buka Drive</a>@elseif($item->drive_sync_status === 'failed')<form method="post" action="{{ route('meeting-submissions.retry-sync', $item) }}" class="mt-2">@csrf<button class="font-black text-rose-600">Coba Sinkronkan Lagi</button></form>@endif</div>@if($item->note)<p class="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{{ $item->note }}</p>@endif<form method="post" action="{{ route('meeting-submissions.grade', $item) }}" class="mt-4 space-y-3">@csrf @method('PUT')<label class="block text-sm font-bold">Nilai (maks. {{ $meetingAssignment->max_score }})<input type="number" name="score" min="0" max="{{ $meetingAssignment->max_score }}" required value="{{ $item->score }}" class="mt-1 w-full rounded-xl border-slate-300"></label><label class="block text-sm font-bold">Komentar<textarea name="feedback" rows="3" class="mt-1 w-full rounded-xl border-slate-300">{{ $item->feedback }}</textarea></label><button class="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Simpan Nilai</button></form></article>@empty<div class="rounded-3xl bg-white p-8 text-center text-slate-500 lg:col-span-2">Belum ada karya yang dikumpulkan.</div>@endforelse</div></section>
@endif
@endsection
