@extends('layouts.app')
@section('title', 'Pengaturan Akademik')
@section('content')
<div class="mb-7"><p class="text-sm font-black uppercase tracking-widest text-indigo-500">Data Master</p><h1 class="text-3xl font-black text-slate-950">Pengaturan Akademik</h1><p class="mt-2 max-w-3xl text-slate-500">Kelola program, cabang, dan periode tanpa mengubah kode aplikasi. Menonaktifkan data tidak menghapus kelas atau riwayat lama.</p></div>
<div class="grid gap-6 xl:grid-cols-2">
@php $panels=[['Kategori Program',$categories,'category'],['Program Kelas',$programs,'program'],['Cabang',$branches,'branch'],['Periode Akademik',$periods,'period']]; @endphp
@foreach($panels as [$title,$records,$type])
<section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">{{ $title }}</h2>
  <div class="mt-4 space-y-2">@forelse($records as $record)<div class="flex items-center justify-between gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4"><div><div class="font-black text-slate-900">{{ $record->name }}</div><div class="text-xs text-slate-500">{{ $record->code }} · {{ $record->classrooms_count ?? $record->programs_count ?? 0 }} {{ $type==='category' ? 'program' : 'kelas' }}</div></div><div class="flex items-center gap-2"><span class="rounded-full px-2 py-1 text-xs font-bold {{ $record->is_active ? 'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-500' }}">{{ $record->is_active ? 'Aktif':'Nonaktif' }}</span>@if($canManage)<form method="POST" action="{{ route('academic-settings.toggle', [$type,$record->id]) }}">@csrf @method('PATCH')<button class="rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-black">{{ $record->is_active ? 'Nonaktifkan':'Aktifkan' }}</button></form>@endif</div></div>@empty<p class="text-sm text-slate-500">Belum ada data.</p>@endforelse</div>
  @if($canManage)
  @if($type==='category')<form method="POST" action="{{ route('academic-settings.categories.store') }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input name="name" required placeholder="Nama kategori" class="rounded-xl border border-slate-300 px-3 py-2"><input name="code" placeholder="Kode otomatis" class="rounded-xl border border-slate-300 px-3 py-2"><button class="sm:col-span-2 rounded-xl bg-indigo-600 px-4 py-3 font-black text-white">Tambah Kategori</button></form>
  @elseif($type==='program')<form method="POST" action="{{ route('academic-settings.programs.store') }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<select name="program_category_id" required class="rounded-xl border border-slate-300 px-3 py-2"><option value="">Kategori...</option>@foreach($categories->where('is_active',true) as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><input name="name" required placeholder="Nama program" class="rounded-xl border border-slate-300 px-3 py-2"><input type="number" name="default_capacity" value="20" min="1" required class="rounded-xl border border-slate-300 px-3 py-2"><input name="code" placeholder="Kode otomatis" class="rounded-xl border border-slate-300 px-3 py-2"><button class="sm:col-span-2 rounded-xl bg-indigo-600 px-4 py-3 font-black text-white">Tambah Program</button></form>
  @elseif($type==='branch')<form method="POST" action="{{ route('academic-settings.branches.store') }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input name="name" required placeholder="Nama cabang" class="rounded-xl border border-slate-300 px-3 py-2"><input name="code" required placeholder="Kode cabang" class="rounded-xl border border-slate-300 px-3 py-2"><button class="sm:col-span-2 rounded-xl bg-indigo-600 px-4 py-3 font-black text-white">Tambah Cabang</button></form>
  @else<form method="POST" action="{{ route('academic-settings.periods.store') }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input name="name" required placeholder="Nama periode" class="rounded-xl border border-slate-300 px-3 py-2"><input name="code" required placeholder="2026/2027" class="rounded-xl border border-slate-300 px-3 py-2"><input type="date" name="starts_on" class="rounded-xl border border-slate-300 px-3 py-2"><input type="date" name="ends_on" class="rounded-xl border border-slate-300 px-3 py-2"><label class="sm:col-span-2 flex gap-2 text-sm"><input type="checkbox" name="is_default" value="1"> Jadikan periode utama</label><button class="sm:col-span-2 rounded-xl bg-indigo-600 px-4 py-3 font-black text-white">Tambah Periode</button></form>@endif
  @endif
</section>
@endforeach
</div>
@endsection
