<?php
namespace App\Http\Controllers;
use App\Models\{Exam,Question,Subject,Attempt,Answer}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class ExamController extends Controller
{
 private function admin():void{abort_unless(in_array(auth()->user()->role,['admin','super_admin','teacher']),403);}
 public function index(){if(auth()->user()->role==='student')return view('exams.student-index',['exams'=>Exam::withCount('questions')->with(['attempts'=>fn($query)=>$query->where('student_id',auth()->id())->latest()])->where('status','published')->latest()->get()]);$this->admin();return view('exams.index',['exams'=>Exam::withCount(['questions','attempts'])->latest()->get()]);}
 public function create(){ $this->admin(); return view('exams.form',['exam'=>new Exam(['status'=>'published']),'subjects'=>Subject::all(),'questions'=>Question::with(['subject','topic'])->where('status','active')->get()]); }
 public function store(Request $r){$this->admin();$d=$this->valid($r);$ids=$r->validate(['questions'=>'required|array|min:1','questions.*'=>'exists:questions,id'])['questions'];DB::transaction(function()use($d,$ids){$e=Exam::create($d+['created_by'=>auth()->id()]);$e->questions()->sync(collect($ids)->mapWithKeys(fn($id,$i)=>[$id=>['order'=>$i+1]]));});return redirect()->route('exams.index')->with('success','Ujian berhasil dibuat.');}
 public function edit(Exam $exam){$this->admin();return view('exams.form',compact('exam')+['subjects'=>Subject::all(),'questions'=>Question::with(['subject','topic'])->where('status','active')->get()]);}
 public function update(Request $r,Exam $exam){$this->admin();$d=$this->valid($r);$ids=$r->input('questions',[]);$exam->update($d);$exam->questions()->sync(collect($ids)->mapWithKeys(fn($id,$i)=>[$id=>['order'=>$i+1]]));return redirect()->route('exams.index')->with('success','Ujian diperbarui.');}
 private function valid(Request $r):array{return $r->validate(['title'=>'required|max:255','description'=>'nullable|string','subject_id'=>'nullable|exists:subjects,id','duration'=>'required|integer|min:1|max:1440','passing_grade'=>'required|numeric|min:0|max:100','status'=>'required|in:draft,published,closed','show_result'=>'required|in:immediately,after_exam,manual','randomize_questions'=>'boolean','randomize_options'=>'boolean','allow_retake'=>'boolean','allow_resume'=>'boolean']);}
 public function start(Exam $exam){abort_unless(auth()->user()->role==='student'&&$exam->status==='published',403);$old=$exam->attempts()->where('student_id',auth()->id())->where('status','in_progress')->latest()->first();if($old){$deadline=$old->started_at->copy()->addMinutes($exam->duration);if(now()->lt($deadline))return redirect()->route('attempts.show',$old);$this->finish($old);return redirect()->route('exams.index')->with('success','Waktu ujian telah berakhir dan hasil Anda sudah disimpan.');}$completed=$exam->attempts()->where('student_id',auth()->id())->whereIn('status',['submitted','graded'])->latest()->first();if($completed&&!$exam->allow_retake)return redirect()->route('exams.index')->with('success','Ujian ini sudah selesai Anda kerjakan dan tidak dapat dimasuki kembali.');$a=$exam->attempts()->create(['student_id'=>auth()->id(),'started_at'=>now()]);return redirect()->route('attempts.show',$a);}
 public function showAttempt(Attempt $attempt){$this->owns($attempt);if($attempt->status!=='in_progress')return redirect()->route('attempts.result',$attempt);$attempt->load(['exam.questions.options','exam.questions.subject','exam.questions.topic','answers']);$deadline=$attempt->started_at->copy()->addMinutes($attempt->exam->duration);if(now()->gte($deadline)){$this->finish($attempt);return redirect()->route('attempts.result',$attempt)->with('success','Waktu ujian telah berakhir dan hasil Anda sudah disimpan.');}return view('exams.attempt',compact('attempt','deadline'));}
 public function autosave(Request $r,Attempt $attempt){$this->owns($attempt);abort_unless($attempt->status==='in_progress',409);abort_if(now()->gte($attempt->started_at->copy()->addMinutes($attempt->exam->duration)),422,'Waktu habis.');$d=$r->validate(['question_id'=>'required|exists:questions,id','answer'=>'nullable|string|max:50000']);abort_unless($attempt->exam->questions()->whereKey($d['question_id'])->exists(),403);Answer::updateOrCreate(['attempt_id'=>$attempt->id,'question_id'=>$d['question_id']],['answer'=>$d['answer']??'']);return response()->json(['saved'=>true,'at'=>now()->format('H:i:s')]);}
 public function submit(Attempt $attempt){$this->owns($attempt);$this->finish($attempt);return redirect()->route('attempts.result',$attempt);}
 private function finish(Attempt $a):void{if($a->status!=='in_progress')return;$a->load('exam.questions.options','answers');$total=0;$hasEssay=false;foreach($a->exam->questions as $q){$ans=$a->answers->firstWhere('question_id',$q->id);if($q->type==='multiple_choice'){$correct=$q->options->firstWhere('is_correct',true)?->option_label;$score=$ans&&$ans->answer===$correct?$q->score:0;if($ans)$ans->update(['score'=>$score]);$total+=$score;}else $hasEssay=true;}$a->update(['submitted_at'=>now(),'score'=>$total,'status'=>$hasEssay?'submitted':'graded']);}
 public function result(Attempt $attempt){$this->owns($attempt,true);$attempt->load('exam.questions.options','exam.questions.subject','exam.questions.topic','answers','student');return view('exams.result',compact('attempt'));}
 private function owns(Attempt $a,bool $adminAllowed=false):void{if($adminAllowed&&in_array(auth()->user()->role,['admin','super_admin','teacher']))return;abort_unless($a->student_id===auth()->id(),403);}
}
