@extends('layouts.app')
@section('title', 'Anggota Kelas')
@section('content')
<div class="mb-6 flex flex-wrap items-end justify-between gap-4">
  <div><a href="{{ route('classrooms.index') }}" class="text-sm font-bold text-indigo-600">← Kembali ke kelas</a><p class="mt-4 text-xs font-black uppercase tracking-widest text-indigo-500">Anggota & Jadwal</p><h1 class="text-3xl font-black text-slate-950">{{ $classroom->display_name }}</h1><p class="mt-2 text-slate-500">{{ $classroom->program?->category?->name }} · {{ $classroom->branchMaster?->name ?: $classroom->branch }} · {{ $classroom->academicPeriod?->name }}</p></div>
  <div class="rounded-2xl bg-indigo-600 px-6 py-4 text-white"><div class="text-xs font-bold uppercase tracking-wider text-indigo-100">Jumlah siswa</div><div class="text-2xl font-black">{{ $classroom->activeEnrollments->count() }} / {{ $classroom->capacity }}</div></div>
</div>
<div class="grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
  <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
    <h2 class="text-xl font-black">Daftar Siswa</h2><p class="text-sm text-slate-500">Nama siswa yang benar-benar terdaftar di kelompok ini.</p>
    <div class="mt-5 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th class="py-3">Siswa</th><th>Kode</th><th>Masuk</th><th class="text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
      @forelse($classroom->activeEnrollments as $enrollment)<tr><td class="py-4"><div class="font-black text-slate-900">{{ $enrollment->student->name }}</div><div class="text-xs text-slate-500">{{ $enrollment->student->email }}</div></td><td class="font-black text-indigo-700">{{ $enrollment->student->student_code ?: '-' }}</td><td>{{ optional($enrollment->joined_at)->format('d M Y') ?: '-' }}</td><td class="text-right"><form method="POST" action="{{ route('classrooms.remove-student', [$classroom, $enrollment->student]) }}" onsubmit="return confirm('Keluarkan siswa dari kelompok ini? Riwayat tetap disimpan.');">@csrf @method('DELETE')<button class="rounded-xl border border-rose-200 px-3 py-2 font-bold text-rose-600 hover:bg-rose-50">Keluarkan</button></form></td></tr>@empty<tr><td colspan="4" class="py-10 text-center text-slate-500">Belum ada siswa di kelompok ini.</td></tr>@endforelse
    </tbody></table></div>
  </section>
  <div class="space-y-6">
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 class="text-lg font-black">Tambahkan Siswa</h2><p class="mt-1 text-sm text-slate-500">Siswa akan dipindahkan dari kelompok lain pada program yang sama.</p>
      <form method="POST" action="{{ route('classrooms.enroll', $classroom) }}" class="mt-4 space-y-3">@csrf<select name="student_id" required class="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3"><option value="">Pilih siswa...</option>@foreach($availableStudents as $student)<option value="{{ $student->id }}">{{ $student->name }} · {{ $student->student_code ?: $student->email }}</option>@endforeach</select><textarea name="notes" rows="2" placeholder="Catatan (opsional)" class="w-full rounded-2xl border border-slate-300 px-4 py-3"></textarea><button type="submit" class="btn-action btn-primary-solid w-full rounded-2xl px-4 py-3"><i class="fa-solid fa-user-plus"></i>Tempatkan ke Kelas</button></form>
    </section>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 class="text-lg font-black">Jadwal Pertemuan</h2><p class="mt-1 text-sm text-slate-500">Atur hari, jam, serta ruang atau tautan pertemuan.</p>
      <div class="mt-4 space-y-2">@forelse($classroom->schedules as $schedule)<div class="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-3"><div><b>{{ $schedule->day_label }}</b><div class="text-xs text-slate-500">{{ substr($schedule->starts_at, 0, 5) }}–{{ substr($schedule->ends_at, 0, 5) }} · {{ $schedule->room ?: 'Ruang belum diisi' }}</div></div><form method="POST" action="{{ route('classrooms.schedules.destroy', [$classroom, $schedule]) }}">@csrf @method('DELETE')<button class="rounded-xl border border-rose-200 bg-white p-2 text-rose-600" title="Hapus jadwal"><i class="fa-solid fa-trash"></i></button></form></div>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-center text-sm text-slate-500">Jadwal belum dibuat.</div>@endforelse</div>
      <form method="POST" action="{{ route('classrooms.schedules.store', $classroom) }}" class="mt-4 grid grid-cols-2 gap-3">@csrf<select name="day_of_week" required class="col-span-2 rounded-xl border border-slate-300 bg-white px-3 py-2">@foreach(\App\Models\ClassroomSchedule::DAYS as $number => $day)<option value="{{ $number }}" @selected(old('day_of_week') == $number)>{{ $day }}</option>@endforeach</select><input type="time" name="starts_at" value="{{ old('starts_at') }}" required class="rounded-xl border border-slate-300 bg-white px-3 py-2"><input type="time" name="ends_at" value="{{ old('ends_at') }}" required class="rounded-xl border border-slate-300 bg-white px-3 py-2"><input name="room" value="{{ old('room') }}" placeholder="Ruang / link" class="col-span-2 rounded-xl border border-slate-300 bg-white px-3 py-2"><button type="submit" class="btn-action btn-primary-solid col-span-2 w-full rounded-xl px-4 py-3"><i class="fa-solid fa-calendar-plus"></i>Simpan Jadwal</button></form>
    </section>
  </div>
</div>
@endsection
